### ISSUE TITLE
Cannot connect to Rails console

### ISSUE THREAD

**Issue by luizkowalski** [superfly/fly-ruby#23]
hey 👋🏻 
in this new version, I can't log in to the Rails console, I get this error

```ruby
# bin/rails c
/app/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3.1/lib/action_dispatch/middleware/stack.rb:174:in `assert_index': No such middleware to insert after: Fly::Headers (RuntimeError)
	from /app/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3.1/lib/action_dispatch/middleware/stack.rb:109:in `insert_after'
	from /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/configuration.rb:59:in `block in insert_after'
	from /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/configuration.rb:90:in `block in merge_into'
	from /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/configuration.rb:89:in `each'
	from /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/configuration.rb:89:in `merge_into'
	from /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/engine.rb:515:in `block in app'
	from /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/engine.rb:512:in `synchronize'
	from /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/engine.rb:512:in `app'
	from /app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/application/finisher.rb:52:in `block in <module:Finisher>'
```
I thought it could be linked to [this commit](https://github.com/superfly/fly-ruby/commit/7f1ab0108fb130e895cf0963c888b809cec90190) but doesn't look like it.

**Comment by jsierles** [comment]
Ah yeah, it's that commit. The idea here was to ensure the DB on the console matches the VM DB. But we'll need to avoid adding middleware.

**Comment by jsierles** [comment]
This should be fixed on `main`.

**Comment by luizkowalski** [comment]
yup, working fine now. thanks!
